import React, { useState } from 'react';
import { ShieldAlert, Building, Settings, Database, History, Users, MessageSquare, Layers, Save, Download, Upload, RefreshCw, Plus, Trash2, Check, CreditCard, Plane } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { PaymentMethod, ServiceItem } from '../../types';
import { UserManagement } from './UserManagement';
import { AuditHistoryView } from './AuditHistoryView';
import { AutomatedBackupSettings } from './AutomatedBackupSettings';
import { EcommerceTravelRequests } from './EcommerceTravelRequests';
import { formatCurrency } from '../../utils/formatters';
import { api, USE_SERVER_API } from '../../services/apiClient';
interface AdminSettingsProps { defaultTab?: 'business'|'services'|'templates'|'opening'|'users'|'backup'|'audit'|'travel'; }
export const AdminSettings: React.FC<AdminSettingsProps> = ({ defaultTab='business' }) => {
 const {settings,updateSettings,services,updateServices,expenseCategories,updateExpenseCategories,openingBalances,updateOpeningBalance,currentUser}=useApp();
 const [activeTab,setActiveTab]=useState<'business'|'services'|'templates'|'opening'|'users'|'backup'|'audit'|'travel'>(defaultTab);
 const [bizName,setBizName]=useState(settings.name),[bizTagline,setBizTagline]=useState(settings.tagline),[bizAddress,setBizAddress]=useState(settings.address),[bizMobile,setBizMobile]=useState(settings.mobile),[bizWhatsapp,setBizWhatsapp]=useState(settings.whatsapp),[bizEmail,setBizEmail]=useState(settings.email),[invoicePrefix,setInvoicePrefix]=useState(settings.invoicePrefix),[invoiceTerms,setInvoiceTerms]=useState(settings.invoiceTerms),[signatureLabel,setSignatureLabel]=useState(settings.signatureLabel),[logoUrl,setLogoUrl]=useState(settings.logoUrl),[whatsappQrCode,setWhatsappQrCode]=useState(settings.whatsappQrCode||''),[authorizedSignatureUrl,setAuthorizedSignatureUrl]=useState(settings.authorizedSignatureUrl||'');
 const [templates,setTemplates]=useState(settings.templates); const [newServiceName,setNewServiceName]=useState(''); const [newServiceCategory,setNewServiceCategory]=useState<ServiceItem['category']>('Air Ticket'); const [newCatName,setNewCatName]=useState(''); const [saveMessage,setSaveMessage]=useState('');
 const readImage=(file:File|undefined,setter:(v:string)=>void,max=1300000)=>{if(!file)return;if(!file.type.startsWith('image/')){alert('Please select an image file.');return;}if(file.size>max){alert('Please use an image smaller than about 1.3 MB.');return;}const r=new FileReader();r.onload=()=>setter(String(r.result||''));r.readAsDataURL(file);};
 const handleLogoUpload=(f:File|undefined)=>readImage(f,setLogoUrl);
 const handleQrUpload=(f:File|undefined)=>readImage(f,setWhatsappQrCode,2000000);
 const handleSaveBusiness=async(e:React.FormEvent)=>{e.preventDefault();await updateSettings({name:bizName,tagline:bizTagline,address:bizAddress,mobile:bizMobile,whatsapp:bizWhatsapp,email:bizEmail,invoicePrefix,invoiceTerms,signatureLabel,logoUrl,whatsappQrCode,authorizedSignatureUrl});setSaveMessage('Business information saved successfully!');setTimeout(()=>setSaveMessage(''),3000);};
 const handleSaveTemplates=(e:React.FormEvent)=>{e.preventDefault();updateSettings({templates});setSaveMessage('Messaging templates saved successfully!');setTimeout(()=>setSaveMessage(''),3000);};
 const handleAddService=async(e:React.FormEvent)=>{e.preventDefault();if(!newServiceName.trim())return;const s:ServiceItem={id:`srv_${Date.now()}`,name:newServiceName.trim(),category:newServiceCategory,enabled:true,order:services.length+1};try{if(USE_SERVER_API){await api.createService({name:s.name,category:s.category,enabled:true,sortOrder:s.order});window.location.reload();return;}updateServices([...services,s]);setNewServiceName('');}catch(error){alert(error instanceof Error?error.message:'Unable to add service');}};
 const handleToggleService=async(id:string)=>{const updated=services.map(s=>s.id===id?{...s,enabled:!s.enabled}:s);try{if(USE_SERVER_API){const item=services.find(s=>s.id===id);if(!item)return;await api.updateService(id,{enabled:!item.enabled});window.location.reload();return;}updateServices(updated);}catch(error){alert(error instanceof Error?error.message:'Unable to update service');}};
 const handleDeleteService=async(id:string)=>{if(!confirm('Delete this service?'))return;try{if(USE_SERVER_API){await api.disableService(id);window.location.reload();return;}updateServices(services.filter(s=>s.id!==id));}catch(error){alert(error instanceof Error?error.message:'Unable to disable service');}};
 const handleAddExpenseCategory=(e:React.FormEvent)=>{e.preventDefault();if(!newCatName.trim())return;updateExpenseCategories([...expenseCategories,{id:`cat_${Date.now()}`,name:newCatName.trim()}]);setNewCatName('');};
 return <div className="space-y-5">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2"><ShieldAlert className="w-6 h-6 text-blue-600"/><span>Admin Control Panel & System Configuration</span></h1><p className="text-xs sm:text-sm text-slate-500">Business profiles, services catalog, messaging templates, opening balances & audit trail</p></div>{saveMessage&&<div className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-100 text-emerald-800 text-xs font-semibold rounded-lg"><Check className="w-4 h-4 text-emerald-600"/><span>{saveMessage}</span></div>}</div>
  <div className="flex flex-wrap items-center gap-1.5 border-b border-slate-200 pb-2 text-xs font-medium">{([['business','Business Info',Building],['services','Services Catalog',Layers],['templates','WhatsApp & SMS Templates',MessageSquare],['opening','Opening Balances',CreditCard],['users','User Accounts & Permissions',Users],['audit','Audit Trail',History],['backup','Automated Backup & Recovery',Database],['travel','E-commerce Travel Requests',Plane]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setActiveTab(id)} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg ${activeTab===id?'bg-blue-600 text-white font-semibold':'text-slate-600 hover:bg-slate-100'}`}><Icon className="w-3.5 h-3.5"/><span>{label}</span></button>)}</div>
  {activeTab==='business'&&<form onSubmit={handleSaveBusiness} className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs space-y-4"><h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide border-b border-slate-100 pb-2">Company & Agency Identity Settings</h2>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <div><label className="block text-xs font-medium text-slate-700 mb-1">Business Name</label><input required value={bizName} onChange={e=>setBizName(e.target.value)} className="w-full px-3 py-1.5 text-xs font-bold border border-slate-300 rounded-lg"/></div>
    <div><label className="block text-xs font-medium text-slate-700 mb-1">Business Tagline</label><input value={bizTagline} onChange={e=>setBizTagline(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
    <div className="sm:col-span-2"><label className="block text-xs font-medium text-slate-700 mb-1">Business Logo</label><div className="flex flex-wrap items-center gap-3"><div className="w-16 h-16 rounded-xl border border-slate-200 bg-slate-50 flex items-center justify-center overflow-hidden">{logoUrl?<img src={logoUrl} alt="Business logo" className="w-full h-full object-contain"/>:<span className="text-[10px] text-slate-400">No Logo</span>}</div><div className="space-y-1"><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>handleLogoUpload(e.target.files?.[0])} className="block w-full text-xs"/><p className="text-[10px] text-slate-400">Upload your agency logo, then Save Configuration.</p></div></div></div>
    <div className="sm:col-span-2"><label className="block text-xs font-medium text-slate-700 mb-1">WhatsApp QR Code for E-Ticket</label><div className="flex flex-wrap items-center gap-3"><div className="w-24 h-24 rounded-xl border border-slate-200 bg-slate-50 flex items-center justify-center overflow-hidden">{whatsappQrCode?<img src={whatsappQrCode} alt="WhatsApp QR" className="w-full h-full object-contain"/>:<span className="text-[10px] text-slate-400 text-center px-2">No QR uploaded</span>}</div><div><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>handleQrUpload(e.target.files?.[0])} className="block w-full text-xs"/><p className="text-[10px] text-slate-400 mt-1">This QR will appear on printed invoices beside the invoice-verification QR.</p></div></div></div>
    <div className="sm:col-span-2"><label className="block text-xs font-medium text-slate-700 mb-1">Authorized Officer Signature (Upload)</label><div className="flex flex-wrap items-center gap-3"><div className="w-40 h-16 rounded-lg border border-slate-200 bg-slate-50 flex items-center justify-center overflow-hidden">{authorizedSignatureUrl?<img src={authorizedSignatureUrl} alt="Authorized officer signature" className="max-w-full max-h-full object-contain"/>:<span className="text-[10px] text-slate-400">No signature uploaded</span>}</div><div><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>readImage(e.target.files?.[0],setAuthorizedSignatureUrl,1300000)} className="block w-full text-xs"/><p className="text-[10px] text-slate-400 mt-1">Upload a transparent PNG or clear image, then click Save Configuration.</p></div></div></div>
    <div><label className="block text-xs font-medium text-slate-700 mb-1">Agency Phone / Helpline</label><input value={bizMobile} onChange={e=>setBizMobile(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
    <div><label className="block text-xs font-medium text-slate-700 mb-1">WhatsApp Number</label><input value={bizWhatsapp} onChange={e=>setBizWhatsapp(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
    <div><label className="block text-xs font-medium text-slate-700 mb-1">Email Address</label><input type="email" value={bizEmail} onChange={e=>setBizEmail(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
    <div><label className="block text-xs font-medium text-slate-700 mb-1">Invoice Number Prefix</label><input value={invoicePrefix} onChange={e=>setInvoicePrefix(e.target.value)} className="w-full px-3 py-1.5 text-xs font-mono uppercase font-bold border border-slate-300 rounded-lg"/></div>
   </div>
   <div><label className="block text-xs font-medium text-slate-700 mb-1">Agency Physical Address</label><input value={bizAddress} onChange={e=>setBizAddress(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
   <div><label className="block text-xs font-medium text-slate-700 mb-1">Invoice Terms & Conditions</label><textarea rows={4} value={invoiceTerms} onChange={e=>setInvoiceTerms(e.target.value)} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg"/></div>
   <div className="flex justify-end pt-3 border-t border-slate-100"><button type="submit" className="flex items-center gap-1.5 px-5 py-2 text-xs font-semibold text-white bg-blue-600 rounded-lg"><Save className="w-4 h-4"/>Save Configuration</button></div>
  </form>}
  {activeTab==='services'&&<div className="space-y-5"><div className="p-4 bg-white border border-slate-200 rounded-xl"><h3 className="text-xs font-bold text-slate-900 uppercase mb-3">Add New Service</h3><form onSubmit={handleAddService} className="flex flex-wrap items-center gap-3"><input required placeholder="e.g. Saudi Work Visa Stamping, Umrah Package" value={newServiceName} onChange={e=>setNewServiceName(e.target.value)} className="px-3 py-1.5 text-xs border border-slate-300 rounded-lg flex-1 min-w-[200px]"/><select value={newServiceCategory} onChange={e=>setNewServiceCategory(e.target.value as ServiceItem['category'])} className="px-3 py-1.5 text-xs border border-slate-300 rounded-lg bg-white"><option>Air Ticket</option><option>Visa</option><option>Passport</option><option>Digital</option><option>Other</option></select><button type="submit" className="flex items-center gap-1 px-4 py-1.5 text-xs font-semibold text-white bg-blue-600 rounded-lg"><Plus className="w-3.5 h-3.5"/>Add Service</button></form></div><div className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="p-3 bg-slate-50 border-b border-slate-200 font-bold text-xs">Active Services ({services.length})</div><div className="divide-y divide-slate-100">{services.map((s,idx)=><div key={s.id} className="p-3 flex items-center justify-between text-xs"><div className="flex items-center gap-3"><span className="font-mono text-slate-400 w-6">#{idx+1}</span><span className={`font-semibold ${s.enabled?'text-slate-900':'text-slate-400 line-through'}`}>{s.name}</span><span className="text-[10px] font-mono text-slate-500 bg-slate-100 px-2 py-0.5 rounded">{s.category}</span></div><div className="flex items-center gap-2"><button onClick={()=>handleToggleService(s.id)} className="px-2.5 py-1 text-[11px] font-semibold rounded bg-emerald-100 text-emerald-800">{s.enabled?'Enabled':'Disabled'}</button><button onClick={()=>handleDeleteService(s.id)} className="p-1 text-slate-400 hover:text-rose-600"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></div></div>}
  {activeTab==='templates'&&<form onSubmit={handleSaveTemplates} className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs space-y-4"><h3 className="text-sm font-bold text-slate-900 uppercase">WhatsApp, SMS & Email Predefined Templates</h3>{(['invoiceShare','customerDueReminder','vendorDueReminder','paymentReceived','paymentCompletedThankYou','flightReminder','scheduleChangeNotice','refundVoidNotification'] as const).map(k=><div key={k}><label className="block text-xs font-semibold text-slate-700 mb-1">{k}</label><textarea rows={3} value={templates[k]||''} onChange={e=>setTemplates({...templates,[k]:e.target.value})} className="w-full px-3 py-1.5 text-xs border border-slate-300 rounded-lg font-mono"/></div>)}<div className="flex justify-end"><button type="submit" className="flex items-center gap-1.5 px-5 py-2 text-xs font-semibold text-white bg-blue-600 rounded-lg"><Save className="w-4 h-4"/>Save Templates</button></div></form>}
  {activeTab==='opening'&&<div className="bg-white border border-slate-200 rounded-xl p-6 shadow-xs space-y-4"><h3 className="text-sm font-bold text-slate-900 uppercase">Manual Opening Balances Setup</h3><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{(Object.keys(openingBalances) as PaymentMethod[]).map(method=><div key={method} className="p-3 border border-slate-200 rounded-xl bg-slate-50"><label className="block text-xs font-semibold text-slate-700 mb-1">{method} Opening Balance (৳)</label><input type="number" min="0" defaultValue={openingBalances[method]} onBlur={e=>updateOpeningBalance(method,Number(e.target.value)||0)} className="w-full px-3 py-1.5 text-sm font-bold font-mono border border-slate-300 rounded-lg bg-white"/></div>)}</div></div>}
  {activeTab==='users'&&<UserManagement/>}{activeTab==='audit'&&<AuditHistoryView/>}{activeTab==='backup'&&<AutomatedBackupSettings/>}{activeTab==='travel'&&<EcommerceTravelRequests/>}
 </div>;
};
