import React, { useEffect, useState } from 'react';
import { CheckCircle2, XCircle, RefreshCw, Save, CreditCard, Users, PackageOpen } from 'lucide-react';
import { api } from '../../services/apiClient';

export const SaasSubscriptionAdmin: React.FC = () => {
  const [data,setData]=useState<any>({users:[],payments:[],plans:[],paymentSettings:{}});
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [editing,setEditing]=useState<any>(null);
  const saveUser=async()=>{if(!editing)return;setBusy(true);try{await api.editSaasUser(editing.id,editing);setNotice('Registration details updated successfully.');setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update registration.');}finally{setBusy(false);}};
  const activateTrial=async(id:string)=>{if(!confirm('Activate this 1 Month Free trial now?'))return;setBusy(true);try{await api.activateSaasFreeTrial(id);setNotice('Free trial activated and congratulations email sent.');await load();}catch(e){setError(e instanceof Error?e.message:'Free trial activation failed.');}finally{setBusy(false);}};
  const load=async()=>{setBusy(true);setError('');try{setData(await api.adminSaas());}catch(e){setError(e instanceof Error?e.message:'Unable to load SaaS management.');}finally{setBusy(false);}};
  useEffect(()=>{void load();},[]);
  const approve=async(id:string)=>{if(!confirm('Approve this payment and activate the subscription?'))return;setBusy(true);try{await api.approveSaasPayment(id);setNotice('Payment approved and subscription activated.');await load();}catch(e){setError(e instanceof Error?e.message:'Approval failed.');}finally{setBusy(false);}};
  const reject=async(id:string)=>{const reason=prompt('Reason for rejection:','Payment proof rejected');if(reason===null)return;setBusy(true);try{await api.rejectSaasPayment(id,reason);setNotice('Payment rejected.');await load();}catch(e){setError(e instanceof Error?e.message:'Rejection failed.');}finally{setBusy(false);}};
  const savePlan=async(p:any)=>{try{await api.updateSaasPlan(p.id,{price:Number(p.price),active:p.active!==false});setNotice(p.name+' package updated.');await load();}catch(e){setError(e instanceof Error?e.message:'Package update failed.');}};
  const saveSettings=async()=>{try{await api.updateSaasPaymentSettings(data.paymentSettings);setNotice('Payment instructions updated.');}catch(e){setError(e instanceof Error?e.message:'Payment settings update failed.');}};
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl sm:text-2xl font-extrabold text-slate-900">SaaS Subscription & Payment Management</h1><p className="text-xs text-slate-500 mt-1">Verify customer payments, manage packages, and control subscription activation.</p></div><button onClick={()=>void load()} disabled={busy} className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700">{error}</div>}
    {notice&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-700">{notice}</div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><PackageOpen className="h-5 w-5 text-emerald-600"/><h2 className="font-extrabold text-slate-900">Packages</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.plans.map((p:any)=><div key={p.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="font-extrabold">{p.name}</div><label className="mt-3 block text-[10px] font-bold uppercase text-slate-500">Price (BDT)<input type="number" min="0" value={p.price} onChange={e=>setData((d:any)=>({...d,plans:d.plans.map((x:any)=>x.id===p.id?{...x,price:e.target.value}:x)}))} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold"/></label><button onClick={()=>void savePlan(p)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-2 text-xs font-extrabold text-white"><Save className="h-3.5 w-3.5"/>Save</button></div>)}</div></section>
    {(data.notificationCount||0)>0&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><div className="text-sm font-extrabold text-amber-900">🔔 Free Trial Activation Reminder</div><div className="mt-2 space-y-2 text-xs text-amber-800">{(data.freeTrials||[]).filter((x:any)=>x.reminderDue||x.deadlinePassed).map((x:any)=><div key={x.subscription_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white/70 p-3"><div><b>{x.business_name}</b> — {x.email}<div className="mt-1">{x.deadlinePassed?'24-hour activation deadline passed.':'12+ hours pending — please review and activate within 24 hours.'}</div></div><button onClick={()=>void activateTrial(x.subscription_id)} disabled={busy} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-extrabold text-white">Activate Free Trial</button></div>)}</div></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-violet-600"/><h2 className="font-extrabold text-slate-900">Registered Users & Businesses</h2></div><span className="text-[10px] font-bold text-slate-500">{data.users.length} registered</span></div><div className="space-y-3">{data.users.map((u:any)=><div key={u.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3 text-xs sm:grid-cols-2 lg:grid-cols-4"><Info label="Business" value={u.business_name}/><Info label="Owner" value={u.owner_name||u.full_name}/><Info label="Email" value={u.email}/><Info label="Username" value={u.username}/><Info label="Phone" value={u.phone}/><Info label="Business Type" value={u.business_type}/><Info label="Status" value={u.is_active?'ACTIVE':'INACTIVE'}/><Info label="Email OTP" value={u.email_verified?'VERIFIED':'NOT VERIFIED'}/><Info label="Registration" value={u.registration_status}/><Info label="Organization" value={u.organization_status}/></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setEditing({...u,fullName:u.full_name,businessName:u.business_name||'',ownerName:u.owner_name||u.full_name,address:u.address||'',businessType:u.business_type||'',website:u.website||'',facebook:u.facebook||'',photo:u.photo||u.logo_url||'',emailVerified:u.email_verified})} className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-extrabold text-white">Edit Registration</button>{!u.is_active&&<button onClick={()=>setEditing({...u,isActive:true,resetFailedLogin:true})} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-extrabold text-white">Unlock & Activate</button>}{u.is_active&&u.registration_status==='approved'&&<button onClick={()=>setEditing({...u,isActive:false})} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-extrabold text-white">Deactivate</button>}</div></div>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><CreditCard className="h-5 w-5 text-sky-600"/><h2 className="font-extrabold text-slate-900">Payment Instructions</h2></div><div className="grid gap-4 sm:grid-cols-2"><Field label="bKash Number" value={data.paymentSettings.bkashNumber||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,bkashNumber:v}}))}/><Field label="Bank Name" value={data.paymentSettings.bankName||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,bankName:v}}))}/><Field label="Bank Account Name" value={data.paymentSettings.bankAccountName||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,bankAccountName:v}}))}/><Field label="Bank Account Number" value={data.paymentSettings.bankAccountNumber||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,bankAccountNumber:v}}))}/><Field label="Bank Branch" value={data.paymentSettings.bankBranch||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,bankBranch:v}}))}/><Field label="Instructions" value={data.paymentSettings.instructions||''} onChange={(v:string)=>setData((d:any)=>({...d,paymentSettings:{...d.paymentSettings,instructions:v}}))}/></div><button onClick={()=>void saveSettings()} className="mt-4 flex items-center gap-2 rounded-xl bg-sky-600 px-4 py-2 text-xs font-extrabold text-white"><Save className="h-4 w-4"/>Save Payment Settings</button></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><Users className="h-5 w-5 text-violet-600"/><h2 className="font-extrabold text-slate-900">Payment Verification Queue</h2></div><div className="space-y-4">{data.payments.length===0?<div className="rounded-xl bg-slate-50 p-5 text-center text-xs text-slate-500">No subscription payments submitted yet.</div>:data.payments.map((p:any)=><div key={p.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3 text-xs sm:grid-cols-2 lg:grid-cols-4"><Info label="Business" value={p.business_name}/><Info label="Owner" value={p.owner_name}/><Info label="Email" value={p.email}/><Info label="Package" value={p.plan_name}/><Info label="Amount" value={'৳'+Number(p.amount||0).toLocaleString()}/><Info label="Method" value={p.method}/><Info label="Sender Account" value={p.sender_account}/><Info label="Transaction ID" value={p.transaction_id}/><Info label="Status" value={p.status}/><Info label="Submitted" value={p.submitted_at?new Date(p.submitted_at).toLocaleString():''}/></div>{p.payment_slip&&<div className="mt-4 rounded-xl bg-slate-50 p-3"><div className="mb-2 text-[10px] font-bold uppercase text-slate-500">Payment Slip</div>{String(p.payment_slip).startsWith('data:image/')?<img src={p.payment_slip} alt="Payment slip" className="max-h-80 max-w-full rounded-lg object-contain"/>:String(p.payment_slip).startsWith('data:application/pdf')?<iframe src={p.payment_slip} title="Payment slip PDF" className="h-96 w-full rounded-lg border bg-white"/>:<a href={p.payment_slip} target="_blank" rel="noreferrer" className="text-xs font-bold text-sky-600">Open payment slip</a>}</div>}{p.rejection_reason&&<div className="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">Rejection: {p.rejection_reason}</div>}{p.status==='pending'&&<div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>void approve(p.id)} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-extrabold text-white"><CheckCircle2 className="h-4 w-4"/>Approve & Activate</button><button disabled={busy} onClick={()=>void reject(p.id)} className="flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2 text-xs font-extrabold text-white"><XCircle className="h-4 w-4"/>Reject</button></div>}</div>)}</div></section>
  </div>{editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-extrabold">Edit Signup / Registration</h2><button onClick={()=>setEditing(null)} className="rounded-xl border px-3 py-1 text-xs font-bold">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Full Name" value={editing.fullName||''} onChange={(v:string)=>setEditing({...editing,fullName:v})}/><Field label="Owner Name" value={editing.ownerName||''} onChange={(v:string)=>setEditing({...editing,ownerName:v})}/><Field label="Business Name" value={editing.businessName||''} onChange={(v:string)=>setEditing({...editing,businessName:v})}/><Field label="Email" value={editing.email||''} onChange={(v:string)=>setEditing({...editing,email:v})}/><Field label="Username" value={editing.username||''} onChange={(v:string)=>setEditing({...editing,username:v})}/><Field label="Phone" value={editing.phone||''} onChange={(v:string)=>setEditing({...editing,phone:v})}/><Field label="Business Type" value={editing.businessType||''} onChange={(v:string)=>setEditing({...editing,businessType:v})}/><Field label="Website" value={editing.website||''} onChange={(v:string)=>setEditing({...editing,website:v})}/><Field label="Facebook" value={editing.facebook||''} onChange={(v:string)=>setEditing({...editing,facebook:v})}/><Field label="Photo / Logo" value={editing.photo||''} onChange={(v:string)=>setEditing({...editing,photo:v})}/><div className="sm:col-span-2"><Field label="Address" value={editing.address||''} onChange={(v:string)=>setEditing({...editing,address:v})}/></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setEditing({...editing,emailVerified:true})} className="rounded-xl border px-4 py-2 text-xs font-bold">Mark Email Verified</button><button onClick={()=>setEditing({...editing,isActive:true,resetFailedLogin:true,registrationStatus:'approved'})} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-extrabold text-white">Activate & Reset Lock</button><button onClick={()=>setEditing({...editing,isActive:false})} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-extrabold text-white">Deactivate</button><button onClick={()=>void saveUser()} disabled={busy} className="rounded-xl bg-sky-600 px-5 py-2 text-xs font-extrabold text-white">Save All Changes</button></div></div></div></>;
};
const Field=({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void})=><label className="block text-[10px] font-bold uppercase text-slate-500">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-800"/></label>;
const Info=({label,value}:{label:string;value:any})=><div><div className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-0.5 break-words font-semibold text-slate-800">{String(value??'—')}</div></div>;
